#!/usr/bin/env node

/**
 * Simple interactive setup to get your Supabase keys
 * and create a working .env.local file
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  blue: '\x1b[34m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
};

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt) {
  return new Promise(resolve => {
    rl.question(prompt, resolve);
  });
}

function log(color, message) {
  console.log(color + message + colors.reset);
}

async function main() {
  console.clear();
  log(colors.blue + colors.bright, '\n🚀 UAEMART - Quick Setup Wizard\n');

  log(colors.yellow, '📋 You need 4 pieces of information from Supabase:');
  log(colors.yellow, '   1. Project URL');
  log(colors.yellow, '   2. Anon Public Key');
  log(colors.yellow, '   3. Service Role Key');
  log(colors.yellow, '   4. Database Connection String\n');

  log(colors.green, '📖 Get these from: https://app.supabase.com');
  log(colors.green, '   → Click your project');
  log(colors.green, '   → Settings → API (for 1,2,3)');
  log(colors.green, '   → Settings → Database (for 4)\n');

  const supabaseUrl = await question(colors.bright + '1️⃣  Paste Project URL: ' + colors.reset);
  if (!supabaseUrl.includes('supabase.co')) {
    log(colors.red, '❌ Invalid URL. Should contain "supabase.co"');
    rl.close();
    process.exit(1);
  }

  const anonKey = await question(colors.bright + '2️⃣  Paste Anon Public Key: ' + colors.reset);
  if (anonKey.length < 50) {
    log(colors.red, '❌ Key too short. Should be a long JWT token');
    rl.close();
    process.exit(1);
  }

  const serviceRoleKey = await question(colors.bright + '3️⃣  Paste Service Role Key: ' + colors.reset);
  if (serviceRoleKey.length < 50) {
    log(colors.red, '❌ Key too short. Should be a long JWT token');
    rl.close();
    process.exit(1);
  }

  const databaseUrl = await question(colors.bright + '4️⃣  Paste Database Connection String: ' + colors.reset);
  if (!databaseUrl.includes('postgresql')) {
    log(colors.red, '❌ Invalid connection string. Should start with "postgresql://"');
    rl.close();
    process.exit(1);
  }

  rl.close();

  // Generate secrets
  const jwtSecret = crypto.randomBytes(32).toString('hex');
  const nextAuthSecret = crypto.randomBytes(32).toString('hex');

  const envContent = `# Auto-generated by setup wizard
# Generated: ${new Date().toISOString()}

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
DATABASE_URL=${databaseUrl}

# Security Keys (auto-generated)
JWT_SECRET=${jwtSecret}
NEXTAUTH_SECRET=${nextAuthSecret}

# Application URLs
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:3000/api
NEXT_PUBLIC_DOMAIN=localhost:3000

# Configuration
ADMIN_EMAIL=admin@uaemart.com
NODE_ENV=development
NEXT_PUBLIC_ENV=development

# Feature Flags
NEXT_PUBLIC_ENABLE_REGISTRATION=true
NEXT_PUBLIC_ENABLE_SELLER_REGISTRATION=true
NEXT_PUBLIC_ENABLE_REVIEWS=true
NEXT_PUBLIC_ENABLE_SUBSCRIPTIONS=false
NEXT_PUBLIC_ENABLE_PAYMENTS=false
`;

  const envPath = path.join(__dirname, '..', '.env.local');
  fs.writeFileSync(envPath, envContent);

  console.clear();
  log(colors.green + colors.bright, '✅ SUCCESS!\n');
  log(colors.green, '✓ .env.local file created with your credentials');
  log(colors.green, '✓ Security keys auto-generated\n');

  log(colors.bright, '🚀 Next steps:\n');
  log(colors.blue, '  1. npm install');
  log(colors.blue, '  2. npm run db:setup');
  log(colors.blue, '  3. npm run dev\n');

  log(colors.yellow, '🌐 Then visit: http://localhost:3000\n');

  log(colors.green, '📝 Login with:');
  log(colors.green, '   Email: admin@uaemart.com');
  log(colors.green, '   Password: Admin@123\n');

  log(colors.yellow, '⚠️  Change the password after first login!\n');
}

main().catch(err => {
  log(colors.red, '❌ Error: ' + err.message);
  process.exit(1);
});
